version: "3.7"
services:
  db:
    image: postgres:15-alpine3.17
    ports:
      - 7432:5432
    restart: always
    container_name: gptdb
    env_file:
      - .postgres.env
    volumes:
      - ./blogData:/var/lib/postgresql/data
  
  app:
    depends_on: 
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gpt
    env_file:
      - .env
    expose:
      - 5864
    volumes:
      - ./logs:/home/node/logs
    networks:
      - proxy

networks:
  proxy:
    external: true
