---
version: '3.7'
services:
  gpt:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gpt
    restart: always
    volumes:
      - ./log:/home/node/src/logs
    expose:
      - 4000
    env_file:
      - .env
    networks:
      - proxy

  db:
    image: postgres:15-alpine3.17
    ports:
      - 7432:5432
    restart: always
    container_name: gpt_db
    env_file:
      - .postgres.env
    volumes:
      - ./blogData:/var/lib/postgresql/data
networks:
  proxy:
    external: true